# Generated by Django 6.0.5 on 2026-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_budget_month_budget_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='monthly_budget',
            new_name='total_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
