# Generated by Django 6.0.5 on 2026-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_monthly_budget_budget_total_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
