# Generated by Django 6.0.5 on 2026-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_budget_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='note',
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
