# Generated by Django 6.0.5 on 2026-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_budget_note_expense_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
